name: ocr_ticket_scanner
description: Application mobile pour scanner et analyser des tickets avec OCR.

publish_to: 'none' # Pour ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  image_picker: ^0.8.7+5
  path_provider: ^2.1.1
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  image: ^4.1.3
  flutter_image_compress: ^2.0.3
  flutter_secure_storage: ^9.2.4
  flutter_login: ^5.0.0
  provider: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Ajoutez vos assets ici si nécessaire
  # assets:
  #   - assets/images/

