name: ocr_ticket_scanner
description: Application mobile pour scanner et analyser des tickets avec OCR.

publish_to: 'none' # Pour ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image: ^4.1.3  # Ajout correct de la dépendance image

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Ajoutez vos assets ici si nécessaire
  # assets:
  #   - assets/images/
